# Generated by Django 5.2.6 on 2025-09-15 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_delete_products'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='product',
        #     name='id',
        #     field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        # ),
        migrations.RemoveField(model_name='product', name='id'),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
