# Generated by Django 5.2.6 on 2025-09-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
    ]
